# Generated by Django 5.1.6 on 2025-02-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Adansonia Digitata-Monkey Bread-Bouye', 'Adansonia Digitata-Monkey Bread-Bouye'), ('Garlic', 'Garlic'), ('Eggplant', 'Eggplant'), ('Bananas', 'Bananas'), ('Beetroot', 'Beetroot'), ('Peanut Butter', 'Peanut Butter'), ('Cabbage', 'Cabbage'), ('Cloves', 'Cloves'), ('Cucumbers', 'Cucumbers'), ('Zucchini', 'Zucchini'), ('Fresh Dates', 'Fresh Dates'), ('Detarium senegalense-Ditax', 'Detarium senegalense-Ditax'), ('Ginger', 'Ginger'), ('Okra', 'Okra'), ('Guava', 'Guava'), ('Green Beans', 'Green Beans'), ('Yam', 'Yam'), ('Jujube (Ziziphus mauritiana Lam.)-Sidem', 'Jujube (Ziziphus mauritiana Lam.)-Sidem'), ('Madd', 'Madd'), ('Mangoes', 'Mangoes'), ('Cassava', 'Cassava'), ('Melon', 'Melon'), ('Turnip', 'Turnip'), ('Cowpea', 'Cowpea'), ('Parsley', 'Parsley'), ('Petit cola (Garcinia kola)', 'Petit cola (Garcinia kola)'), ('Fresh Peppers', 'Fresh Peppers'), ('Leek', 'Leek'), ('Cashew Apple', 'Cashew Apple'), ('Vetiver Roots', 'Vetiver Roots'), ('Lettuce-Salads', 'Lettuce-Salads'), ('Tiger Nut-Ndir', 'Tiger Nut-Ndir'), ('Tamarind Pods (Dakkhar)', 'Tamarind Pods (Dakkhar)'), ('Black Tamarind or Dialium guineense-Solom', 'Black Tamarind or Dialium guineense-Solom'), ('Nana Green Tea', 'Nana Green Tea'), ('Tomatoes', 'Tomatoes')], db_index=True, help_text='Name of the product', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Raw', 'Raw'), ('Processed', 'Processed')], default='Raw', help_text='Type of product', max_length=100),
        ),
    ]
