# Generated by Django 5.1.6 on 2025-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, help_text='Country or region of origin', max_length=255, null=True),
        ),
    ]
