# Generated by Django 5.1.6 on 2025-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_alter_product_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, default=None, help_text='Unique barcode identifier', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
