# Generated by Django 5.1.6 on 2025-03-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
