# Generated by Django 5.1.6 on 2025-03-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_remove_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, default='TEMP_BARCODE', help_text='Unique barcode identifier', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
