# Generated by Django 5.1.6 on 2025-03-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0006_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, help_text='Unique barcode identifier', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='co2',
            field=models.CharField(blank=True, help_text="CO₂ concentration in percentage (e.g., '5.00')", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='humidity_rate',
            field=models.CharField(blank=True, help_text="Humidity rate in percentage (e.g., '50.25')", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='n2',
            field=models.CharField(blank=True, help_text="N₂ concentration in percentage (e.g., '78.00')", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='o2',
            field=models.CharField(blank=True, help_text="O₂ concentration in percentage (e.g., '21.00')", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Stock Keeping Unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_temperature',
            field=models.CharField(blank=True, help_text="Storage temperature in degrees Celsius (e.g., '-2.50')", max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku', 'warehouse'), name='unique_sku_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('barcode', 'warehouse'), name='unique_barcode_per_warehouse'),
        ),
    ]
