# Generated by Django 5.1.6 on 2025-03-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0007_alter_product_barcode_alter_product_co2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_condition',
            field=models.CharField(help_text='Condition of the packaging', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety_or_species',
            field=models.CharField(help_text='Variety or species of the product', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Weight or quantity of the product (in default units)', max_digits=1000000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the product in kilograms', max_digits=100000000000, null=True),
        ),
    ]
