# Generated by Django 5.1.6 on 2025-03-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0008_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging_condition',
            field=models.CharField(blank=True, help_text='Condition of the packaging', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_code',
            field=models.CharField(blank=True, help_text='Code assigned to the supplier', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety_or_species',
            field=models.CharField(blank=True, help_text='Variety or species of the product', max_length=255, null=True),
        ),
    ]
