# Generated by Django 5.1.6 on 2025-03-05 17:59

import apps.managment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0009_alter_product_packaging_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lot_number',
            field=models.CharField(default=apps.managment.models.generate_lot_number, editable=False, help_text='Auto-generated unique lot number for batch identification', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW', 'RAW'), ('PROCESSED', 'PROCESSED')], default='RAW', help_text='Type of product', max_length=100),
        ),
    ]
