# Generated by Django 5.1.6 on 2025-03-07 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0011_alter_product_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the farmer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
