# Generated by Django 5.1.6 on 2025-03-07 12:46

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0012_farmer_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the farmer', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID assigned to the farmer', unique=True),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['farmer_id', 'name'], name='managment_f_farmer__1ce432_idx'),
        ),
    ]
