# Generated by Django 5.1.6 on 2025-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0013_alter_farmer_email_alter_farmer_farmer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Raw', 'Raw'), ('Processed', 'Processed')], default='RAW', help_text='Type of product', max_length=100),
        ),
    ]
