# Generated by Django 5.1.6 on 2025-03-08 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0014_alter_product_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Product Added'), ('UPDATE', 'Product Updated'), ('REMOVE', 'Product Removed'), ('STOCK_OUT', 'Stock Taken Out')], help_text='The type of action performed on the product', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='The date and time when the action occurred')),
                ('quantity_changed', models.DecimalField(blank=True, decimal_places=2, help_text='The quantity added or removed (positive for add, negative for remove)', max_digits=15, null=True)),
                ('previous_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity in stock before the action', null=True)),
                ('new_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity in stock after the action', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional details about the action', null=True)),
                ('product', models.ForeignKey(help_text='The product this log entry pertains to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='managment.product')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Log',
                'verbose_name_plural': 'Product Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
