# Generated by Django 5.1.6 on 2025-03-09 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_is_farmer'),
        ('managment', '0015_productlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Farmer who supplied the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='authentication.farmer'),
        ),
    ]
