# Generated by Django 5.1.6 on 2025-03-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0017_alter_product_farmer_delete_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity available in stock', null=True),
        ),
    ]
