# Generated by Django 5.1.6 on 2025-03-25 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0019_alter_product_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, help_text='Name of the requested product', max_length=255)),
                ('quantity_requested', models.PositiveIntegerField(blank=True, help_text='Number of units requested', null=True)),
                ('weight_requested_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight requested in kilograms', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the request', max_length=20)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when request was made')),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date and time when request was approved', null=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date and time when request was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the request', null=True)),
                ('client', models.ForeignKey(help_text='Client making the request', limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Warehouse where the items are stored', on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='managment.warehouse')),
            ],
            options={
                'verbose_name': 'Item Request',
                'verbose_name_plural': 'Item Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
