# Generated by Django 5.1.6 on 2025-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0020_itemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price of the requested items based on max unit price', max_digits=15, null=True),
        ),
    ]
