# Generated by Django 5.1.6 on 2025-04-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0021_itemrequest_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight per package in kilograms (e.g., weight per bag or sachet)', max_digits=10, null=True),
        ),
    ]
