# Generated by Django 5.1.6 on 2025-04-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0022_product_package_weight_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='package_weight_kg',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_per_bag_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight per bag or container in kilograms (e.g., weight per bag or sachet)', max_digits=10, null=True),
        ),
    ]
