# Generated by Django 5.1.6 on 2025-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0023_remove_product_package_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_per_bag_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight per bag or container in kilograms', max_digits=10, null=True),
        ),
    ]
