# Generated by Django 5.1.6 on 2025-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0024_alter_product_weight_per_bag_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_per_bag_kg',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Weight per bag or container in kilograms', max_digits=10, null=True),
        ),
    ]
