# Generated by Django 5.1.6 on 2025-03-08 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID assigned to the farmer', unique=True)),
                ('name', models.CharField(help_text='Full name of the farmer', max_length=255)),
                ('contact_number', models.CharField(blank=True, help_text='Primary contact number of the farmer', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address of the farmer', max_length=255, null=True, unique=True)),
                ('address', models.TextField(help_text='Physical address of the farmer')),
                ('farm_name', models.CharField(blank=True, help_text='Name of the farm', max_length=255, null=True)),
                ('farm_location', models.CharField(help_text='Geographical location of the farm', max_length=255)),
                ('total_land_area', models.DecimalField(blank=True, decimal_places=2, help_text='Total area of the farm in hectares', max_digits=10, null=True)),
                ('certifications', models.TextField(blank=True, help_text='List of certifications held by the farmer', null=True)),
                ('compliance_standards', models.TextField(blank=True, help_text='Compliance standards followed by the farmer', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about the farmer', null=True)),
                ('registration_date', models.DateField(blank=True, help_text='Date of Registration', null=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
        ),
    ]
