# Generated by Django 5.1.6 on 2025-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_farmer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a farmer'),
        ),
    ]
