# Generated by Django 5.1.6 on 2025-03-12 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_is_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a client'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(help_text='Unique auto-incremented ID for the client', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User/company name', max_length=255)),
                ('user_type', models.CharField(choices=[('Producteur', 'Producer'), ('Transformateur', 'Processor'), ('Acheteur Local', 'Local Buyer'), ('Acheteur Régional', 'Regional Buyer'), ('Acheteur International', 'International Buyer')], help_text='User role in ecosystem', max_length=22)),
                ('email', models.EmailField(help_text='Contact email', max_length=255, unique=True)),
                ('phone', models.CharField(help_text='Direct contact number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address/geolocation', null=True)),
                ('country', models.CharField(default='Senegal', help_text='Origin country for international buyers', max_length=100)),
                ('account_status', models.CharField(choices=[('Actif', 'Active'), ('Inactif', 'Inactive'), ('Suspendu', 'Suspended')], default='Active', help_text='Account status', max_length=10)),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the client', unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about the client', null=True)),
                ('registration_date', models.DateField(blank=True, help_text='Date of Registration', null=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'db_table_comment': 'Central registry for all platform actors',
                'indexes': [models.Index(fields=['user_type'], name='client_user_ty_d8ad3a_idx'), models.Index(fields=['account_status'], name='client_account_ce260e_idx')],
            },
        ),
    ]
