# Generated by Django 5.1.6 on 2025-03-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_is_client_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', help_text='Account status', max_length=10),
        ),
    ]
